name: CI

on:
  push:
    branches: main
    tags: "*/v*"
  pull_request:
    branches: "**"

jobs:
  build:
    name: ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - ros1
          - rosbag
          - rosbag2
          - rosbag2-node
          - rosbag2-web
          - rosmsg
          - rosmsg-msgs-common
          - rosmsg-serialization
          - rosmsg2-serialization
          - rostime
          - xmlrpc

    runs-on: ubuntu-latest

    permissions:
      contents: read
      # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: yarn

      - run: yarn install --immutable

      - run: yarn workspaces foreach -Rp --topological-dev --from @lichtblick/${{ matrix.package }} run build
      - run: yarn lint:ci packages/${{ matrix.package }}
      - run: yarn workspace @lichtblick/${{ matrix.package }} run test

      - name: build xmlrpc examples
        if: ${{ matrix.package == 'xmlrpc' }}
        run: yarn install --immutable && yarn tsc -b
        working-directory: packages/xmlrpc/examples

      - name: Publish to NPM (dry run)
        run: yarn workspace @lichtblick/${{ matrix.package }} npm publish --provenance --access public --dry-run
